### ISSUE TITLE
src/Tomorrow-ExtraBold.glyphs: "Non-existent glyph class public.kern1.P found in kerning rules."

### ISSUE THREAD

**Issue by felipesanches** [MonicaRizzolli/Tomorrow#18]
https://travis-ci.com/MonicaRizzolli/Tomorrow/builds/129961754

<img width="682" alt="Captura de Tela 2019-10-01 às 23 01 58" src="https://user-images.githubusercontent.com/213676/66012930-95764580-e49f-11e9-8b6e-b7d963911cab.png">

**Comment by felipesanches** [comment]
same thing with `src/Tomorrow-ExtraBoldItalic.glyphs`

**Comment by felipesanches** [comment]
Looking at the glyphsLib source code, I see that the code that emits these warning messages does output the kerning pairs anyway. So it is just merely a warning indeed.

![Screenshot at 2019-10-08 21:50:23](https://user-images.githubusercontent.com/213676/66443632-5ca21780-ea2f-11e9-9d52-2e25b91981f6.png)


I did not understand exactly what is going wrong with the setting of glyph kern pairs and classes in the `.glyphs` file (or GlyphsApp UI) but it seems that the actual information is not being lost during conversion from `.glyphs` to `.ufo`.

Any idea, @anthrotype? @schriftgestalt?

**Comment by anthrotype** [comment]
The kern pairs are written out to ufo.kerning despite they reference kerning groups that are missing from ufo.groups (the latter public.kern1 and 2 are exported in a previous method from Glyphs' MMK_L and MMK_R kern classes).
But the problem remains, since ufo2ft kernFeatureWriter will inevitably ignore such kern pairs referencing missing groups when generating the GPOS kern feature.

I concur that the warning message is misleading because it is complaining that "public.kern{1,2}" are missing in the .glyphs source, whereas in Glyphs.app's Kerning window they are not prefixed like that.

Anyway, I believe the Kerning window has a "Clean up" feature that will remove such invalid pairs, although I'm not 100% sure. You should try and check that you don't inadvertently lose other data.

**Comment by MonicaRizzolli** [comment]
I believe the "Clean up" feature worked.

**Comment by felipesanches** [comment]
I am not super familiar with the syntax of the kerning data on a .glyphs file, but this was the result of the cleanup operation:
https://github.com/MonicaRizzolli/Tomorrow/commit/efa58e95bc1d040405e7bbb9bfdee14e13cab01f

**Comment by felipesanches** [comment]
And this has indeed caused the glyphsLib message to not show up anymore during the build: https://travis-ci.com/MonicaRizzolli/Tomorrow/builds/131121091

**Comment by bghryct** [comment]
Not the same project but I do want to add that running cleanup in the Glyphs UI does seem to squash this error.
