### ISSUE TITLE
Fix FontBakery FAILs

### ISSUE THREAD

**Issue by davelab6** [MonicaRizzolli/Tomorrow#8]
https://travis-ci.com/MonicaRizzolli/Tomorrow/builds/127404952 has 162 FAILs. These must be fixed.

**Comment by davelab6** [comment]
File names like `Tomorrow-BlackOblique.ttf` are not valid; they must be eg `Tomorrow-BlackItalic.ttf`

**Comment by felipesanches** [comment]
I can help you guys with those fixes. Let's schedule a day for us to get together and work on them!

**Comment by felipesanches** [comment]
The count actually increased because not all font files were being checked. So we're at 189 FAILs right now at https://travis-ci.com/felipesanches/Tomorrow/builds/128431824

But we'll take care of it all ;-)

**Comment by felipesanches** [comment]
with this license name id fix (https://github.com/MonicaRizzolli/Tomorrow/issues/4#issuecomment-533525658) the FAIL count is now at 154

**Comment by felipesanches** [comment]
@MonicaRizzolli added two more font files, `Tomorrow-BoldItalic.glyphs` and `Tomorrow-SemiBoldItalic.glyphs`, which are the last ones that were still missing in this family.

With that, our FAIL count has increased back to 164 FAILs. But the good news is that this is our final step to get this family prepared for release. I will spend some time on this family this week.

**Comment by felipesanches** [comment]
with https://github.com/felipesanches/Tomorrow/commit/ba45350ae0783f8d1b6164a25531bd31af96ef77 we fixed 34 FAILs related to the gasp table.

We're now at 130 FAILs.

**Comment by felipesanches** [comment]
with https://github.com/felipesanches/Tomorrow/commit/a7de76afd357b12a10946be3c5b060ff70347eba we fixed 17 FAILs related to the lack of a dummy signature.

We're now at 113 FAILs.

**Comment by felipesanches** [comment]
with https://github.com/felipesanches/Tomorrow/commit/380c5eeee2b4d45699853da5edff9feb99ee7556 we fixed 4 FAILs related to canonical file naming rules. Some source files had a good glyphs filename, but bad settings that made fontmake output badly named TTFs.

We're now at 109 FAILs.

**Comment by felipesanches** [comment]
At https://github.com/felipesanches/Tomorrow/commit/5631743b9d113193ef5761ee3956fdf47408b090 I added the -i option to the fontmake command line so that the instance specific custom-parameters are not ignored during build. This fixed 14 more FAILs.

So, now the FAIL count is at 95 ;-)

Thanks, @anthrotype for the hint at issue #14!

**Comment by felipesanches** [comment]
At https://github.com/felipesanches/Tomorrow/commit/4f2387796de2054f6d1bb827405fea8f56680d0d the BOLD bit settings in both fsSelection and head.macstyle were fixed.

This brings us down to **81 remaining FAILs** to fix.

**Comment by felipesanches** [comment]
OK! I addressed the problem from issue #17 ("no axes defined" for the regular and the italic) at https://github.com/felipesanches/Tomorrow/commit/086576391e1fe7b9cacf588a00d6c1d55478755a. This resulted in those 2 font files being properly built and brought with it a few extra FAILs, but this is progress!

**We're at 88 FAILs...**

**Comment by felipesanches** [comment]
At https://github.com/felipesanches/Tomorrow/commit/5ebc1f75c9ec3a3fc24d3a23c5e14598d98b800b I fixed the value of italic angle for all italics to 10 degrees. I think GlyphsApp should be able to auto-detect and set these values...

We're at 79 FAILs now.

**Comment by felipesanches** [comment]
At https://github.com/felipesanches/Tomorrow/commit/9a13ca928c644ef863288fe66a5c12c289793d16 I have fixed all name table entries that had issues and, with that, we're down to **54 FAILs!**

**Comment by felipesanches** [comment]
After fixing a fontbakery bug (https://github.com/googlefonts/fontbakery/issues/2650), two false-FAILs are gone!

And at https://github.com/felipesanches/Tomorrow/commit/ad9246f0108f4265566183c2801474d8a2936ee3 we are now with **52 FAILs.**

**Comment by felipesanches** [comment]
At https://github.com/felipesanches/Tomorrow/commit/bcd44b9bdb0d0081826b09fcd9e99a02cb6cb61b I have declared the 0x000D codepoint of the CARRIAGE RETURN char in all `.glyphs`files so that now all 16 glyph coverage FAILs are fixed.

With this, we have only **36 remaining FAILs** to fix. These are 18 instances (one per font file) of these two failed metrics checks:

<img width="672" alt="Captura de Tela 2019-10-02 às 03 21 02" src="https://user-images.githubusercontent.com/213676/66022254-b486ce80-e4c3-11e9-90cb-1a1d98aee762.png">

**Comment by felipesanches** [comment]
https://github.com/felipesanches/Tomorrow/commit/5a4614130bac5bbeb86308afe315b82a9834999a fixes all remaining FAILs.

The project is clean now! :-D

I will now take a look at the 45 WARNs to see if there are things to address there as well.

**Comment by felipesanches** [comment]
@MonicaRizzolli please close this issue.

**Comment by felipesanches** [comment]
There were a few checks disabled in the build script because we originally did not have a DESCRIPTION.en_us.html and a METADATA.pb file.

I've created the METADATA.pb now (and we have added the html weeks ago) and re-enabled those checks. We have, then, yet another 48 FAILs to fix here...

https://travis-ci.com/MonicaRizzolli/Tomorrow/builds/130091268

**Comment by felipesanches** [comment]
After fixing some bad URLs and copyright strings at https://github.com/felipesanches/Tomorrow/commit/0ab152ba26d834830bc127567b874e2d140b7a6e we now have just 12 remaining FAILs to be fixed.

**Comment by felipesanches** [comment]
At https://github.com/felipesanches/Tomorrow/commit/8e8e18c0364ad31b7a236f45329745ff7364f62f I fixed the weightClass values on the files and on METADATA.pb and we are again with a fully clean project repo.

Now I will go back look at the WARNs...
